In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_excel('world.xlsx')

In [3]:
data.columns=data.columns.str.replace(' ','_').str.lower()

In [4]:
def cleaning(df, clean):
    for i in clean:
        # Convert the column to string first to avoid errors
        df[i] = df[i].astype(str).str.lstrip('$')
        df[i] = df[i].str.replace(',', '', regex=False)
        df[i] = df[i].str.rstrip('%')
        df[i] = pd.to_numeric(df[i], errors='coerce')  # Convert to float, handling errors
    return df

In [5]:
clean=['business_tax_rate','gdp','health_exp/capita','tourism_inbound','tourism_outbound']
cleaning(data,clean)

,birth_rate,business_tax_rate,co2_emissions,country,days_to_start_business,ease_of_business,energy_usage,gdp,health_exp_%_gdp,health_exp/capita,...,life_expectancy_male,mobile_phone_usage,number_of_records,population_0-14,population_15-64,population_65+,population_total,population_urban,tourism_inbound,tourism_outbound
0,0.020,NaN,87931.0,Algeria,NaN,NaN,26998.0,5.479006e+10,0.035,60.0,...,67.0,0.0,1,0.342,0.619,0.039,31719449,0.599,1.020000e+08,1.930000e+08
1,0.050,NaN,9542.0,Angola,NaN,NaN,7499.0,9.129595e+09,0.034,22.0,...,44.0,0.0,1,0.476,0.499,0.025,13924930,0.324,3.400000e+07,1.460000e+08
2,0.043,NaN,1617.0,Benin,NaN,NaN,1983.0,2.359122e+09,0.043,15.0,...,53.0,0.0,1,0.454,0.517,0.029,6949366,0.383,7.700000e+07,5.000000e+07
3,0.027,NaN,4276.0,Botswana,NaN,NaN,1836.0,5.788312e+09,0.047,152.0,...,49.0,0.1,1,0.383,0.587,0.029,1755375,0.532,2.270000e+08,2.090000e+08
4,0.046,NaN,1041.0,Burkina Faso,NaN,NaN,NaN,2.610959e+09,0.051,12.0,...,49.0,0.0,1,0.468,0.505,0.028,11607944,0.178,2.300000e+07,3.000000e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2699,NaN,NaN,NaN,Turks and Caicos Islands,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1,NaN,NaN,NaN,32427,0.911,NaN,NaN
2700,0.013,46.4,NaN,United States,5.0,4.0,2132446.0,1.624460e+13,0.179,8895.0,...,76.0,1.0,1,0.196,0.667,0.136,313873685,0.811,2.000920e+11,1.265730e+11
2701,0.015,41.9,NaN,Uruguay,7.0,85.0,NaN,5.000435e+10,0.089,1308.0,...,74.0,1.5,1,0.220,0.639,0.140,3395253,0.948,2.222000e+09,1.028000e+09
2702,0.020,61.9,NaN,"Venezuela, RB",144.0,180.0,NaN,3.812862e+11,0.046,593.0,...,72.0,1.0,1,0.288,0.652,0.060,29954782,0.889,9.040000e+08,3.202000e+09
2703,0.011,NaN,NaN,Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,...,76.0,NaN,1,0.206,0.641,0.152,105275,0.949,NaN,NaN

In [6]:
null_values=pd.DataFrame(data.isnull().sum(),columns=['sum_of_null'])
null_values['percentage']=(null_values['sum_of_null']/data.shape[0]) * 100
t=null_values.sort_values(by='sum_of_null',ascending=False)
t

                        sum_of_null  percentage
ease_of_business               2519   93.158284
hours_to_do_tax                1288   47.633136
business_tax_rate              1281   47.374260
days_to_start_business          986   36.464497
energy_usage                    919   33.986686
lending_interest                824   30.473373
co2_emissions                   579   21.412722
tourism_outbound                471   17.418639
tourism_inbound                 368   13.609467
health_exp_%_gdp                309   11.427515
health_exp/capita               309   11.427515
infant_mortality_rate           260    9.615385
population_0-14                 220    8.136095
population_65+                  220    8.136095
population_15-64                220    8.136095
gdp                             210    7.766272
internet_usage                  173    6.397929
mobile_phone_usage              167    6.176036
life_expectancy_male            136    5.029586
life_expectancy_female          136    5.029586
birth_rate                      119    4.400888
population_urban                 26    0.961538
number_of_records                 0    0.000000
population_total                  0    0.000000
country                           0    0.000000

In [7]:
data['business_tax_rate	'] = data['business_tax_rate'].fillna(data.groupby('country')['business_tax_rate'].transform('mean'))

In [8]:
(data.isnull().mean().round(4) * 100)

birth_rate                 4.40
business_tax_rate         47.37
co2_emissions             21.41
country                    0.00
days_to_start_business    36.46
ease_of_business          93.16
energy_usage              33.99
gdp                        7.77
health_exp_%_gdp          11.43
health_exp/capita         11.43
hours_to_do_tax           47.63
infant_mortality_rate      9.62
internet_usage             6.40
lending_interest          30.47
life_expectancy_female     5.03
life_expectancy_male       5.03
mobile_phone_usage         6.18
number_of_records          0.00
population_0-14            8.14
population_15-64           8.14
population_65+             8.14
population_total           0.00
population_urban           0.96
tourism_inbound           13.61
tourism_outbound          17.42
business_tax_rate\t       11.06
dtype: float64

In [9]:
data.drop(['ease_of_business'],axis=1)

,birth_rate,business_tax_rate,co2_emissions,country,days_to_start_business,energy_usage,gdp,health_exp_%_gdp,health_exp/capita,hours_to_do_tax,...,mobile_phone_usage,number_of_records,population_0-14,population_15-64,population_65+,population_total,population_urban,tourism_inbound,tourism_outbound,business_tax_rate\t
0,0.020,NaN,87931.0,Algeria,NaN,26998.0,5.479006e+10,0.035,60.0,NaN,...,0.0,1,0.342,0.619,0.039,31719449,0.599,1.020000e+08,1.930000e+08,73.7125
1,0.050,NaN,9542.0,Angola,NaN,7499.0,9.129595e+09,0.034,22.0,NaN,...,0.0,1,0.476,0.499,0.025,13924930,0.324,3.400000e+07,1.460000e+08,52.1000
2,0.043,NaN,1617.0,Benin,NaN,1983.0,2.359122e+09,0.043,15.0,NaN,...,0.0,1,0.454,0.517,0.029,6949366,0.383,7.700000e+07,5.000000e+07,71.0875
3,0.027,NaN,4276.0,Botswana,NaN,1836.0,5.788312e+09,0.047,152.0,NaN,...,0.1,1,0.383,0.587,0.029,1755375,0.532,2.270000e+08,2.090000e+08,18.7250
4,0.046,NaN,1041.0,Burkina Faso,NaN,NaN,2.610959e+09,0.051,12.0,NaN,...,0.0,1,0.468,0.505,0.028,11607944,0.178,2.300000e+07,3.000000e+07,45.4875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2699,NaN,NaN,NaN,Turks and Caicos Islands,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,NaN,NaN,NaN,32427,0.911,NaN,NaN,NaN
2700,0.013,46.4,NaN,United States,5.0,2132446.0,1.624460e+13,0.179,8895.0,175.0,...,1.0,1,0.196,0.667,0.136,313873685,0.811,2.000920e+11,1.265730e+11,46.4000
2701,0.015,41.9,NaN,Uruguay,7.0,NaN,5.000435e+10,0.089,1308.0,310.0,...,1.5,1,0.220,0.639,0.140,3395253,0.948,2.222000e+09,1.028000e+09,41.9000
2702,0.020,61.9,NaN,"Venezuela, RB",144.0,NaN,3.812862e+11,0.046,593.0,792.0,...,1.0,1,0.288,0.652,0.060,29954782,0.889,9.040000e+08,3.202000e+09,61.9000
2703,0.011,NaN,NaN,Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,0.206,0.641,0.152,105275,0.949,NaN,NaN,NaN

In [10]:
X = data.drop('country',axis=1)
y = data[['country']]

In [11]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=1)
imputer.fit(X)

KNNImputer(n_neighbors=1)

In [12]:
X_imputed = imputer.transform(X)

In [13]:
X_imputed = pd.DataFrame(X_imputed, columns = X.columns)

In [14]:
X_imputed.isna().sum()

birth_rate                0
business_tax_rate         0
co2_emissions             0
days_to_start_business    0
ease_of_business          0
energy_usage              0
gdp                       0
health_exp_%_gdp          0
health_exp/capita         0
hours_to_do_tax           0
infant_mortality_rate     0
internet_usage            0
lending_interest          0
life_expectancy_female    0
life_expectancy_male      0
mobile_phone_usage        0
number_of_records         0
population_0-14           0
population_15-64          0
population_65+            0
population_total          0
population_urban          0
tourism_inbound           0
tourism_outbound          0
business_tax_rate\t       0
dtype: int64

In [15]:
df_final = pd.concat([X_imputed, y], axis=1)

In [16]:
df_final

,birth_rate,business_tax_rate,co2_emissions,days_to_start_business,ease_of_business,energy_usage,gdp,health_exp_%_gdp,health_exp/capita,hours_to_do_tax,...,number_of_records,population_0-14,population_15-64,population_65+,population_total,population_urban,tourism_inbound,tourism_outbound,business_tax_rate\t,country
0,0.020,39.7,87931.0,13.0,147.0,26998.0,5.479006e+10,0.035,60.0,336.0,...,1.0,0.342,0.619,0.039,31719449.0,0.599,1.020000e+08,1.930000e+08,73.7125,Algeria
1,0.050,39.7,9542.0,13.0,147.0,7499.0,9.129595e+09,0.034,22.0,336.0,...,1.0,0.476,0.499,0.025,13924930.0,0.324,3.400000e+07,1.460000e+08,52.1000,Angola
2,0.043,42.2,1617.0,40.0,74.0,1983.0,2.359122e+09,0.043,15.0,52.0,...,1.0,0.454,0.517,0.029,6949366.0,0.383,7.700000e+07,5.000000e+07,71.0875,Benin
3,0.027,42.2,4276.0,40.0,74.0,1836.0,5.788312e+09,0.047,152.0,52.0,...,1.0,0.383,0.587,0.029,1755375.0,0.532,2.270000e+08,2.090000e+08,18.7250,Botswana
4,0.046,84.5,1041.0,84.0,147.0,765.0,2.610959e+09,0.051,12.0,216.0,...,1.0,0.468,0.505,0.028,11607944.0,0.178,2.300000e+07,3.000000e+07,45.4875,Burkina Faso
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2699,0.013,42.2,161.0,40.0,74.0,76.0,2.671401e+09,0.033,2718.0,52.0,...,1.0,0.292,0.637,0.071,32427.0,0.911,4.890000e+08,1.400000e+08,42.2000,Turks and Caicos Islands
2700,0.013,46.4,91118.0,5.0,4.0,2132446.0,1.624460e+13,0.179,8895.0,175.0,...,1.0,0.196,0.667,0.136,313873685.0,0.811,2.000920e+11,1.265730e+11,46.4000,United States
2701,0.015,41.9,737.0,7.0,85.0,19986.0,5.000435e+10,0.089,1308.0,310.0,...,1.0,0.220,0.639,0.140,3395253.0,0.948,2.222000e+09,1.028000e+09,41.9000,Uruguay
2702,0.020,61.9,91118.0,144.0,180.0,27086.0,3.812862e+11,0.046,593.0,792.0,...,1.0,0.288,0.652,0.060,29954782.0,0.889,9.040000e+08,3.202000e+09,61.9000,"Venezuela, RB"
2703,0.011,58.7,99.0,16.0,102.0,81.0,2.558908e+08,0.120,292.0,128.0,...,1.0,0.206,0.641,0.152,105275.0,0.949,2.500000e+07,7.000000e+06,58.7000,Virgin Islands (U.S.)

In [17]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2704 entries, 0 to 2703
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   birth_rate              2704 non-null   float64
 1   business_tax_rate       2704 non-null   float64
 2   co2_emissions           2704 non-null   float64
 3   days_to_start_business  2704 non-null   float64
 4   ease_of_business        2704 non-null   float64
 5   energy_usage            2704 non-null   float64
 6   gdp                     2704 non-null   float64
 7   health_exp_%_gdp        2704 non-null   float64
 8   health_exp/capita       2704 non-null   float64
 9   hours_to_do_tax         2704 non-null   float64
 10  infant_mortality_rate   2704 non-null   float64
 11  internet_usage          2704 non-null   float64
 12  lending_interest        2704 non-null   float64
 13  life_expectancy_female  2704 non-null   float64
 14  life_expectancy_male    2704 non-null   float64
 15  mobile_phone_usage      2704 non-null   float64
 16  number_of_records       2704 non-null   float64
 17  population_0-14         2704 non-null   float64
 18  population_15-64        2704 non-null   float64
 19  population_65+          2704 non-null   float64
 20  population_total        2704 non-null   float64
 21  population_urban        2704 non-null   float64
 22  tourism_inbound         2704 non-null   float64
 23  tourism_outbound        2704 non-null   float64
 24  business_tax_rate	      2704 non-null   float64
 25  country                 2704 non-null   object
dtypes: float64(25), object(1)
memory usage: 549.4+ KB

In [18]:
df_final.to_csv('clean_data.csv')